services:
  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongo-devops-app
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - devops-network
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  mongo-express:
    image: mongo-express
    container_name: mongo-express-devops-app
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/devops-node
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_MONGODB_SERVER: devops-node
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - devops-network
    depends_on:
      mongodb:
        condition: service_healthy
  app:
    build:
      context: .
    container_name: "nodejs-devops-app"
    ports:
      - '4000:3000'
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - devops-network
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local

networks:
  devops-network:
    driver: bridge